version: "2"

services:
  foodmenu:
    build:
      context: .
    image: foodmenu_server
    shm_size: '2gb'
    environment:
      SKIP_SELENIUM_QUIT: ${SKIP_SELENIUM_QUIT}
    ports:
      - "8081:3001"
    restart: unless-stopped